Improvements to adaptive rebase policy

diff --git a/lexec_lnx b/lexec_lnx
--- a/lexec_lnx
+++ b/lexec_lnx
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% The server script
+
 # ========================= static configuration
 # the directory on the remote machine source trees $HOMEDIR/cvc4-*
 HOMEDIR="/space/ajreynol"
@@ -9,7 +11,7 @@ BASEBUILDDIR="/tmp/ajreynol/cmake"
 THISEXEC="lexec_lnx"
 # ========================= end static configuration
 
-# %%% BEGIN DO NOT MODIFY THIS COPY, USE client VERSION
+# %%% BEGIN DO NOT MODIFY THIS COPY, USE CLIENT VERSION
 # ================================================== shared method library
 # Compute the git source info of directory $1
 # Store result in $INFOSRC / $INFOSRCCOMMIT / $INFOSRCCHANGED / $INFOSTRING
@@ -28,8 +30,39 @@ function computeSrcInfo
     INFOSTRING="[$INFOSRC ${INFOSRCCOMMIT:0:8}]"
   fi
 }
+# Compute build information (binary name and configure options) for given source prefix $1 and build type $2
+# Store result in $BINARYNAME / $CARGS
+function computeBuildInfo
+{
+  BASEBINARYNAME="cvc4"
+  if [ $2 = "prod" ]; then
+    # production has the default prefix
+    BINARYPREFIX=""
+    CARGS="production --static --program-prefix="
+  elif [ $2 = "debug" ]; then
+    BINARYPREFIX="d-"
+    CARGS="debug --static --no-unit-testing --program-prefix=d-"
+  elif [ $2 = "debug-unit" ]; then
+    BINARYPREFIX="du-"
+    CARGS="debug --program-prefix=du-"
+  elif [ $2 = "profile" ]; then
+    BINARYPREFIX="prof-"
+    CARGS="production --static --profiling --program-prefix=prof-"
+  else
+    echo "$THISEXEC: ERROR: unknown build type $2"
+    exit 1
+  fi
+  # if there is a prefix
+  if [ ! -z $1 ]; then
+    # add the src prefix if it exists
+    BINARYPREFIX="$BINARYPREFIX$1-"
+    CARGS="$CARGS$1-"
+  fi
+  # binary name is used for remote install and double checking git scm
+  BINARYNAME="$BINARYPREFIX$BASEBINARYNAME"
+}
 # ================================================== end shared method library
-# %%% END DO NOT MODIFY THIS COPY, USE client VERSION
+# %%% END DO NOT MODIFY THIS COPY, USE CLIENT VERSION
 
 # usage: lexec_lnx [build type] (-p [prefix])? [command] [sync options] [command options]
 echo "=== $THISEXEC $@"
@@ -98,21 +131,30 @@ if [ X$1 = X'-r' ]; then
   REBASE="true"
   shift;
 fi
-# get the proactive branch
+# get the adaptive syncronization
 if [ ! -z "$REQUIRESSYNC" ]; then
   if [ ! -z $LOCALBRANCHREF ]; then
     if [ $LOCALBRANCHREF != $INFOSRC ]; then
-      # requires branching
+      # the remote branch doesn't match, so force a git branch
       echo "$THISEXEC: requires branch"
       BRANCH=$LOCALBRANCHREF
       BRANCHFORCE="true"
     fi
     if [ ! -z $LOCALCOMMITREF ]; then
       if [ $LOCALCOMMITREF != ${INFOSRCCOMMIT:0:8} ]; then
-        # requires rebasing
+        # the remote commit doesn't match, so force a git rebase
         echo "$THISEXEC: requires rebasing"
         REBASE="true"
         REBASEFORCE="true"
+      fi
+      if [ ! -z "$INFOSRCCHANGED" ]; then
+        # local is clean but remote is dirty (strange case where local reverted to clean after sync in a dirty state, on the same commit)
+        if [ ! -z $LOCALNOMODIFIED ]; then
+          # just force rebasing to correct
+          echo "$THISEXEC: requires rebasing (local was reverted)"
+          REBASE="true"
+          REBASEFORCE="true"
+        fi
       fi
     fi
   fi
@@ -164,37 +206,41 @@ if [ ! -z "$REQUIRESSYNC" ]; then
         echo "$THISEXEC: ERROR: branch [$LOCALBRANCHREF] commit mismatch: local [$LOCALCOMMITREF], remote [${INFOSRCCOMMIT:0:8}], use -r to sync."
         exit 1
       fi
-    fi
-    # we are now ensured that the branch/commit matches on local and remote
-    # now, ensure we are in the same source code modification state (clean/dirty)
-    if [ ! -z "$INFOSRCCHANGED" ]; then
-      # remote is clean, probably forgot to sync changes from local
-      if [ -z $LOCALNOMODIFIED ]; then
-        # we know the sync is wrong, so this is an error
-        SYNCERROR="local is dirty, but remote src is clean, use -s sync or commit changes locally to proceed"
+      # we are now ensured that the branch/commit matches on local and remote
+      # now, ensure we are in the same source code modification state (clean/dirty)
+      if [ ! -z "$INFOSRCCHANGED" ]; then
+        # local is clean but remote is dirty (strange case where local reverted to clean after sync in a dirty state, on the same commit)
+        if [ ! -z $LOCALNOMODIFIED ]; then
+          # we know the sync is wrong, so this is an error
+          SYNCERROR="local is clean, but remote src is dirty"
+        fi
+        # incremental modifications should continue to use manual sync -s
+        if [ -z $LOCALSYNC ]; then
+          # the sync may have been correct if local did not have any further changes, hence this is a warning
+          SYNCWARNING="local did not use sync -s and remote src is dirty"
+        fi
+      else
+        # remote is clean, probably forgot to sync changes from local
+        if [ -z $LOCALNOMODIFIED ]; then
+          # we know the sync is wrong, so this is an error
+          SYNCERROR="local is dirty, but remote src is clean, use -s X or commit changes locally to proceed"
+        fi
       fi
     else
-      # local is clean but remote is dirty (strange case where local reverted to clean after sync in a dirty state, on the same commit)
-      if [ ! -z $LOCALNOMODIFIED ]; then
-        # we know the sync is wrong, so this is an error
-        SYNCERROR="local is clean, but remote src is dirty"
-      fi
-      # incremental modifications should continue to use manual sync -s
-      if [ -z $LOCALSYNC ]; then
-        # the sync may have been correct if local did not have any further changes, hence this is a warning
-        SYNCWARNING="local did not use sync -s and remote src is dirty"
-      fi
+      # internal error, should never happen
+      SYNCERROR="local did not provide a commit number"
     fi
+
     if [ ! -z "$SYNCERROR" ]; then
-      echo "$THISEXEC: ERROR: $SYNCERROR (branch [$LOCALBRANCHREF] commit [${INFOSRCCOMMIT:0:8}])"
+      echo "$THISEXEC: ERROR: $SYNCERROR (branch [$LOCALBRANCHREF] commit [$LOCALCOMMITREF])"
       exit 1;
     fi
     if [ ! -z "$SYNCWARNING" ]; then
-      echo "$THISEXEC: WARNING: $SYNCWARNING (branch [$LOCALBRANCHREF] commit [${INFOSRCCOMMIT:0:8}])"
+      echo "$THISEXEC: WARNING: $SYNCWARNING (branch [$LOCALBRANCHREF] commit [$LOCALCOMMITREF])"
     fi
   fi
   echo "==============================================="
-  echo "REMOTE ISSUE: $COMMAND"
+  echo "RUN COMMAND: $COMMAND"
   echo "REMOTE SOURCE: $INFOSTRING"
   echo "==============================================="
 fi
@@ -202,31 +248,7 @@ fi
 
 
 # ========================= compute build and configuration information
-BINARYNAME="cvc4"
-if [ ! -z $SRCPREFIX ]; then
-  BINARYNAME="$SRCPREFIX-$BINARYNAME"
-fi
-if [ $BUILDTYPE = "prod" ]; then
-  BINARYNAME="$BINARYNAME"
-  CARGS="production --static --program-prefix="
-elif [ $BUILDTYPE = "debug" ]; then
-  BINARYNAME="d-$BINARYNAME"
-  CARGS="debug --static --no-unit-testing --program-prefix=d-"
-elif [ $BUILDTYPE = "debug-unit" ]; then
-  BINARYNAME="du-$BINARYNAME"
-  CARGS="debug --program-prefix=du-"
-elif [ $BUILDTYPE = "profile" ]; then
-  BINARYNAME="prof-$BINARYNAME"
-  CARGS="production --static --profiling --program-prefix=prof-"
-else
-  echo "$THISEXEC: ERROR: unknown build type $BUILDTYPE"
-  exit 1
-fi
-if [ -z $SRCPREFIX ]; then
-  CARGS="$CARGS"
-else
-  CARGS="$CARGS$SRCPREFIX-"
-fi
+computeBuildInfo $SRCPREFIX $BUILDTYPE
 echo "$THISEXEC: binary name is $BINARYNAME"
 # ========================= end compute build and configuration information
 
@@ -306,7 +328,7 @@ if [[ "$COMMAND" =~ ^(install|regress|ctest|units|info)$ ]]; then
     INFOFULLSTRING="$INFOFULLSTRING, BINARY: $INFOBINARY"
   fi
   echo "==============================================="
-  echo "COMMAND COMPLETE: $COMMAND"
+  echo "FINISHED: $COMMAND"
   echo "$INFOFULLSTRING"
   echo "==============================================="
 fi
